name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build, tag image for DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: my-image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .

  manual_approval:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    needs: build
    

    steps:
      - name: Manual Approval
        id: manual_approval_step
        run: echo "Please approve the image push to DockerHub"

  deploy:
    runs-on: ubuntu-latest
    needs: manual_approval
    if: github.event_name == 'workflow_dispatch' && ${{ needs.manual_approval.outputs.manual_approval_step == 'success' }}

    steps:
      - name: Push image to DockerHub
        if: success()
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: my-image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
